name: PrisonTycoon
version: 1.0.0
main: fr.prisoncore.prisoncore.prisonTycoon.PrisonTycoon
author: PrisonCore
description: Plugin de minage avec pioche légendaire et enchantements custom
website: https://prisoncore.fr
api-version: '1.21'

# Serveur supporté
folia-supported: false

# Dépendances (aucune pour ce plugin)
softdepend: []
depend: []

# Permissions
permissions:
  # Permissions joueurs
  specialmine.pickaxe:
    description: Permet d'obtenir la pioche légendaire
    default: true

  specialmine.mine:
    description: Permet d'utiliser les commandes de mine de base
    default: true

  # Permissions administrateur
  specialmine.admin:
    description: Accès complet aux fonctionnalités administrateur
    default: op
    children:
      - specialmine.pickaxe
      - specialmine.mine
      - specialmine.admin.givetokens
      - specialmine.admin.reload
      - specialmine.admin.economy

  specialmine.admin.givetokens:
    description: Permet de donner des tokens aux joueurs
    default: op

  specialmine.admin.reload:
    description: Permet de recharger la configuration
    default: op

  specialmine.admin.economy:
    description: Permet de voir les statistiques économiques
    default: op

# Commandes
commands:
  pickaxe:
    description: Obtenir la pioche légendaire
    usage: /pickaxe
    permission: specialmine.pickaxe
    permission-message: §cVous n'avez pas la permission d'utiliser cette commande!

  mine:
    description: Gérer les mines
    usage: /mine <generate|list|info|stats> [nom]
    permission: specialmine.mine
    permission-message: §cVous n'avez pas la permission d'utiliser cette commande!
    aliases: [mines, prisonmine]

  givetokens:
    description: Donner des tokens à un joueur (ADMIN)
    usage: /givetokens <joueur> <quantité>
    permission: specialmine.admin.givetokens
    permission-message: §cVous n'avez pas la permission d'utiliser cette commande!
    aliases: [givetoken, addtokens]

  prisontycoon:
    description: Commande principale du plugin
    usage: /prisontycoon [reload|stats|economy|top] [args...]
    aliases: [pt, ptycoon, prison]

# Chargement
load: POSTWORLD
startup: POSTWORLD

# Compatibilité
depend-bootstrap: false