name: PrisonTycoon
version: 1.0.0
main: fr.prisoncore.prisoncore.prisonTycoon.PrisonTycoon
author: PrisonCore
description: Plugin de minage avec pioche légendaire et enchantements custom
website: https://prisoncore.fr
api-version: '1.21'

# Serveur supporté
folia-supported: false

# Dépendances (aucune pour ce plugin)
softdepend: []
depend: []

# Permissions
permissions:
  # --- Permissions pour tous les joueurs ---
  specialmine.pickaxe:
    description: Permet d'obtenir la pioche légendaire via /pickaxe.
    default: true

  specialmine.repair:
    description: Permet d'ouvrir le menu de réparation via /repair.
    default: true

  specialmine.sell:
    description: Permet de vendre des items via /sell.
    default: true

  specialmine.mine:
    description: Accès aux commandes de base pour les mines (/mine list, /mine info, /mine stats).
    default: true

  # --- Permissions hiérarchiques pour l'accès aux mines (à assigner manuellement) ---
  specialmine.mine.a:
    description: Accès à la mine A
    default: false

  specialmine.mine.b:
    description: Accès à la mine B
    default: false

  specialmine.mine.c:
    description: Accès à la mine C
    default: false

  # --- Permissions Administrateur ---
  specialmine.admin.mine.permission:
    description: Permet de gérer les permissions de mine d'autres joueurs.
    default: op

  specialmine.admin.givetokens:
    description: Permet de donner des tokens à un joueur.
    default: op

  specialmine.admin.reload:
    description: Permet de recharger la configuration du plugin.
    default: op

  specialmine.admin.economy:
    description: Permet de gérer l'économie du plugin.
    default: op

  specialmine.admin.mine.generate:
    description: Permet de générer ou de supprimer une mine.
    default: op

  # Permission globale pour les administrateurs
  specialmine.admin:
    description: Accès complet aux fonctionnalités administrateur.
    default: op
    children:
      - specialmine.admin.mine.permission
      - specialmine.admin.givetokens
      - specialmine.admin.reload
      - specialmine.admin.economy
      - specialmine.admin.mine.generate

# Commandes
commands:
  pickaxe:
    description: Obtenir la pioche légendaire.
    usage: /pickaxe
    permission: specialmine.pickaxe
    permission-message: §cVous n'avez pas la permission d'utiliser cette commande!
    aliases: [pioche]

  repair:
    description: Ouvre le menu de réparation de la pioche légendaire.
    usage: /repair
    permission: specialmine.repair
    permission-message: §cVous n'avez pas la permission d'utiliser cette commande!
    aliases: [fix, reparer]

  sell:
    description: Vendre des items.
    usage: /sell <all|hand>
    permission: specialmine.sell
    permission-message: §cVous n'avez pas la permission d'utiliser cette commande!
    aliases: [vendre]

  mine:
    description: Gérer les mines et obtenir des informations.
    usage: /mine <generate|list|info|permission|stats> [nom]
    permission: specialmine.mine
    permission-message: §cVous n'avez pas la permission d'utiliser cette commande!
    aliases: [mines, prisonmine]

  givetokens:
    description: Donner des tokens à un joueur (ADMIN).
    usage: /givetokens <joueur> <quantité>
    permission: specialmine.admin.givetokens
    permission-message: §cVous n'avez pas la permission d'utiliser cette commande!
    aliases: [givetoken, addtokens]

  prisontycoon:
    description: Commande principale du plugin.
    usage: /prisontycoon [reload|stats|economy|top] [args...]
    aliases: [pt, ptycoon, prison]

# Chargement
load: POSTWORLD
startup: POSTWORLD

# Compatibilité
depend-bootstrap: false