name: PrisonTycoon
version: 1.0.0
main: fr.prisontycoon.PrisonTycoon
author: PrisonCore
description: Plugin de minage avec pioche légendaire et enchantements custom
website: https://prisoncore.fr
api-version: '1.21'

# Serveur supporté
folia-supported: false

# Dépendances (aucune pour ce plugin)
softdepend: [ ]
depend: [ ]

# Permissions
permissions:
  # --- Permissions pour tous les joueurs ---
  specialmine.pickaxe:
    description: Permet d'obtenir la pioche légendaire via /pickaxe.
    default: true

  specialmine.repair:
    description: Permet d'ouvrir le menu de réparation via /repair.
    default: true

  specialmine.sell:
    description: Permet de vendre des items via /sell.
    default: true

  specialmine.mine:
    description: Accès aux commandes de base pour les mines (/mine list, /mine info, /mine stats).
    default: true

  # --- Permissions hiérarchiques pour l'accès aux mines (à assigner manuellement) ---
  specialmine.mine.a:
    description: Accès à la mine A
    default: false

  specialmine.mine.b:
    description: Accès à la mine B
    default: false

  specialmine.mine.c:
    description: Accès à la mine C
    default: false

  # --- Permissions Administrateur ---
  specialmine.admin.mine.permission:
    description: Permet de gérer les permissions de mine d'autres joueurs.
    default: op

  specialmine.admin.givetokens:
    description: Permet de donner des tokens à un joueur.
    default: op

  specialmine.admin.reload:
    description: Permet de recharger la configuration du plugin.
    default: op

  specialmine.admin.economy:
    description: Permet de gérer l'économie du plugin.
    default: op

  specialmine.admin.mine.generate:
    description: Permet de générer ou de supprimer une mine.
    default: op

  # NOUVELLES permissions
  specialmine.rankup:
    description: Utiliser le système de rankup
    default: true

  specialmine.chat:
    description: Permet d'envoyer des messages en chat
    default: true

  specialmine.chat.colors:
    description: Permet d'utiliser les codes couleur dans le chat
    default: false

  specialmine.admin.chat:
    description: "Permet d'utiliser les commandes admin du chat"
    default: op
    children:
      - specialmine.admin.mute
      - specialmine.admin.ban
      - specialmine.admin.logs

  specialmine.admin.vip:
    description: "Permet de gérer les joueurs VIP"
    default: op

  specialmine.admin.mute:
    description: "Permet de muter/démuter des joueurs"
    default: op

  specialmine.admin.ban:
    description: "Permet de bannir/débannir des joueurs"
    default: op

  specialmine.admin.logs:
    description: "Permet de consulter les logs du chat"
    default: op

  # PERMISSIONS VIP
  specialmine.vip:
    description: "Permissions de base pour les VIP"
    default: false
    children:
      - specialmine.chat.colors
      - specialmine.chat.hand
      - specialmine.chat.inv
      - specialmine.invsee.use

  specialmine.chat.hand:
    description: "Permet d'utiliser [hand] dans le chat"
    default: false

  specialmine.chat.inv:
    description: "Permet d'utiliser [inv] dans le chat"
    default: false

  specialmine.invsee.use:
    description: "Permet d'utiliser /invsee (lecture seule)"
    default: false

  specialmine.invsee.modify:
    description: "Permet de modifier les inventaires avec /invsee"
    default: op

  # PERMISSIONS ADMIN COMPLÈTES
  specialmine.admin:
    description: "Toutes les permissions admin"
    default: op
    children:
      - specialmine.admin.chat
      - specialmine.admin.vip
      - specialmine.invsee.modify
      - specialmine.chat.colors
      - specialmine.chat.hand
      - specialmine.chat.inv

# Commandes
commands:
  pickaxe:
    description: Obtenir la pioche légendaire.
    usage: /pickaxe
    permission: specialmine.pickaxe
    permission-message: §cVous n'avez pas la permission d'utiliser cette commande!
    aliases: [ pioche ]

  repair:
    description: Ouvre le menu de réparation de la pioche légendaire.
    usage: /repair
    permission: specialmine.repair
    permission-message: §cVous n'avez pas la permission d'utiliser cette commande!
    aliases: [ fix, reparer ]

  sell:
    description: Vendre des items.
    usage: /sell <all|hand>
    permission: specialmine.sell
    permission-message: §cVous n'avez pas la permission d'utiliser cette commande!
    aliases: [ vendre ]

  mine:
    description: Gérer les mines et obtenir des informations.
    usage: /mine <generate|list|info|stats> [nom]
    permission: specialmine.mine
    permission-message: §cVous n'avez pas la permission d'utiliser cette commande!
    aliases: [ mines, prisonmine ]

  givetokens:
    description: Donner des tokens à un joueur (ADMIN).
    usage: /givetokens <joueur> <quantité>
    permission: specialmine.admin.givetokens
    permission-message: §cVous n'avez pas la permission d'utiliser cette commande!
    aliases: [ givetoken, addtokens ]

  prisontycoon:
    description: Commande principale du plugin.
    usage: /prisontycoon [reload|stats|economy|top] [args...]
    aliases: [ pt, ptycoon, prison ]

  conteneur:
    description: Obtenir et gérer les conteneurs de collecte automatique.
    usage: /conteneur <1-5|info|list>
    permission: specialmine.container
    permission-message: §cVous n'avez pas la permission d'utiliser cette commande!
    aliases: [ container, coffre, box ]

  rankup:
    description: Système de montée en rang pour les mines
    usage: /<command> [all|auto|info]

  cristal:
    description: Gère les cristaux.
    usage: /cristal <niveau> [joueur] [type]
    permission: specialmine.admin

  adminchat:
    description: "Commandes administratives pour gérer le chat"
    usage: "/adminchat <mute|unmute|ban|unban|logs|reload|stats|test|broadcast|clear> [arguments]"
    permission: specialmine.admin

  vip:
    description: "Gère les joueurs VIP"
    usage: "/vip <add|remove|list|check> [joueur]"
    permission: specialmine.admin
    aliases: [ setvip, managevip ]

  invsee:
    description: "Voir l'inventaire d'un autre joueur"
    usage: "/invsee <joueur>"
    permission: specialmine.vip
    aliases: [ inv, openinv, viewinv ]

# Chargement
load: POSTWORLD
startup: POSTWORLD

# Compatibilité
depend-bootstrap: false