name: PrisonTycoon
version: 1.0.0
main: fr.prisontycoon.PrisonTycoon
api-version: 1.21
author: PrisonCore
description: Plugin de prison avec système de prestige, mines spéciales et métiers
depend:
  - Multiverse-Core
  - FastAsyncWorldEdit
  - FancyNpcs
softdepend:
  - CustomMobs
  - PlayerShops

# Permissions principales
permissions:
  specialmine.*:
    description: "Accès complet au plugin"
    default: op
    children:
      specialmine.admin: true
      specialmine.vip: true
      specialmine.basic: true

  specialmine.admin:
    description: "Permissions administrateur"
    default: op
    children:
      specialmine.vip: true
      specialmine.mine.generate: true
      specialmine.prestige.admin: true

  specialmine.vip:
    description: "Permissions VIP"
    default: false
    children:
      specialmine.basic: true
      specialmine.rankup.auto: true
      specialmine.mine.vip1: true
      specialmine.mine.vip2: true

  specialmine.basic:
    description: "Permissions de base"
    default: true
    children:
      specialmine.mine.a: true

  # Permission spécifique pour /repair
  specialmine.repair:
    description: "Utiliser /repair (Guerrier niv 5+, cooldown 3h)"
    default: false

  # Permissions de mines (A-Z)
  specialmine.mine.a:
    description: "Accès à la mine A"
    default: true
  specialmine.mine.b:
    description: "Accès à la mine B"
    default: false
  specialmine.mine.c:
    description: "Accès à la mine C"
    default: false
  specialmine.mine.d:
    description: "Accès à la mine D"
    default: false
  specialmine.mine.e:
    description: "Accès à la mine E"
    default: false
  specialmine.mine.f:
    description: "Accès à la mine F"
    default: false
  specialmine.mine.g:
    description: "Accès à la mine G"
    default: false
  specialmine.mine.h:
    description: "Accès à la mine H"
    default: false
  specialmine.mine.i:
    description: "Accès à la mine I"
    default: false
  specialmine.mine.j:
    description: "Accès à la mine J"
    default: false
  specialmine.mine.k:
    description: "Accès à la mine K"
    default: false
  specialmine.mine.l:
    description: "Accès à la mine L"
    default: false
  specialmine.mine.m:
    description: "Accès à la mine M"
    default: false
  specialmine.mine.n:
    description: "Accès à la mine N"
    default: false
  specialmine.mine.o:
    description: "Accès à la mine O"
    default: false
  specialmine.mine.p:
    description: "Accès à la mine P"
    default: false
  specialmine.mine.q:
    description: "Accès à la mine Q"
    default: false
  specialmine.mine.r:
    description: "Accès à la mine R"
    default: false
  specialmine.mine.s:
    description: "Accès à la mine S"
    default: false
  specialmine.mine.t:
    description: "Accès à la mine T"
    default: false
  specialmine.mine.u:
    description: "Accès à la mine U"
    default: false
  specialmine.mine.v:
    description: "Accès à la mine V"
    default: false
  specialmine.mine.w:
    description: "Accès à la mine W"
    default: false
  specialmine.mine.x:
    description: "Accès à la mine X"
    default: false
  specialmine.mine.y:
    description: "Accès à la mine Y"
    default: false
  specialmine.mine.z:
    description: "Accès à la mine Z"
    default: false

  # Permissions mines VIP
  specialmine.mine.vip1:
    description: "Accès à la mine VIP I"
    default: false
  specialmine.mine.vip2:
    description: "Accès à la mine VIP II"
    default: false

  # Permissions prestige
  specialmine.prestige.1:
    description: "Prestige niveau 1"
    default: false
  specialmine.prestige.5:
    description: "Prestige niveau 5"
    default: false
  specialmine.prestige.10:
    description: "Prestige niveau 10"
    default: false
  specialmine.prestige.15:
    description: "Prestige niveau 15"
    default: false
  specialmine.prestige.20:
    description: "Prestige niveau 20"
    default: false
  specialmine.prestige.25:
    description: "Prestige niveau 25"
    default: false
  specialmine.prestige.30:
    description: "Prestige niveau 30"
    default: false
  specialmine.prestige.35:
    description: "Prestige niveau 35"
    default: false
  specialmine.prestige.40:
    description: "Prestige niveau 40"
    default: false
  specialmine.prestige.45:
    description: "Prestige niveau 45"
    default: false
  specialmine.prestige.50:
    description: "Prestige niveau 50"
    default: false

  # Autres permissions
  specialmine.rankup:
    description: "Utiliser /rankup"
    default: true
  specialmine.rankup.auto:
    description: "Auto-rankup (VIP)"
    default: false
  specialmine.sell:
    description: "Utiliser /sell"
    default: true
  specialmine.mine:
    description: "Utiliser /mine"
    default: true
  specialmine.mine.generate:
    description: "Générer les mines (admin)"
    default: op
  specialmine.prestige:
    description: "Utiliser /prestige"
    default: true
  specialmine.prestige.admin:
    description: "Administration prestige"
    default: op

# Commandes du plugin
commands:
  prisontycoon:
    description: "Commande principale du plugin"
    usage: /prisontycoon [reload|stats|economy|top] [args...]
    permission: specialmine.admin

  rankup:
    description: "Système de montée en rang pour les mines (A-Z + FREE)"
    usage: /rankup [all|auto|info|max]
    permission: specialmine.basic
    permission-message: §cVous n'avez pas la permission d'utiliser cette commande!

  adminmine:
    description: "Gérer les mines et obtenir des informations"
    usage: /adminmine <list|tp|info|generate|types|accessible> [nom]
    permission: specialmine.admin
    permission-message: §cVous n'avez pas la permission d'utiliser cette commande!

  prestige:
    description: "Système de prestige - Reset volontaire avec bonus permanents"
    usage: /prestige [info|récompenses|talents|effectuer|confirmer]
    permission: specialmine.basic
    permission-message: §cVous n'avez pas la permission d'utiliser cette commande!

  metier:
    description: "Ouvre le menu des métiers"
    usage: /metier [info|choisir <métier>|help]
    permission: specialmine.basic
    permission-message: §cVous n'avez pas la permission d'utiliser cette commande!
    aliases: [ profession, job, trabajo ]

  changemetier:
    description: "Change de métier (payant, cooldown)"
    usage: /changemetier <mineur|commercant|guerrier>
    permission: specialmine.basic
    permission-message: §cVous n'avez pas la permission d'utiliser cette commande!
    aliases: [ changeprofession, changejob ]

  metierxp:
    description: "Donne de l'XP métier (admin)"
    usage: /metierxp <nombre>
    permission: specialmine.admin
    permission-message: §cVous n'avez pas la permission d'utiliser cette commande!

  playerdata:
    description: "Admin: sauvegarder/charger les données joueur"
    usage: /playerdata <save|load> <joueur>
    permission: specialmine.admin
    permission-message: §cVous n'avez pas la permission d'utiliser cette commande!

  # Commandes existantes conservées
  pickaxe:
    description: "Ouvre le menu de la pioche légendaire"
    usage: /pickaxe
    permission: specialmine.basic
    permission-message: §cVous n'avez pas la permission d'utiliser cette commande!
    aliases: [ pioche ]

  repair:
    description: "Répare gratuitement l'item en main (Guerrier niv 5+, CD 3h)"
    usage: /repair
    permission: specialmine.repair
    permission-message: §cVous n'avez pas la permission d'utiliser cette commande!
    aliases: [ fix ]

  sell:
    description: "Vendre des items"
    usage: /sell <all|hand>
    permission: specialmine.basic
    permission-message: §cVous n'avez pas la permission d'utiliser cette commande!
    aliases: [ vendre ]

  givetokens:
    description: "Donner des tokens à un joueur (ADMIN)"
    usage: /givetokens <joueur> <quantité>
    permission: specialmine.admin
    permission-message: §cVous n'avez pas la permission d'utiliser cette commande!
    aliases: [ givetoken, addtokens ]

  conteneur:
    description: "Obtenir et gérer les conteneurs de collecte automatique"
    usage: /conteneur <1-5|info|list>
    permission: specialmine.basic
    permission-message: §cVous n'avez pas la permission d'utiliser cette commande!
    aliases: [ container, coffre, box ]

  cristal:
    description: "Gère les cristaux"
    usage: /cristal <niveau> [joueur] [type]
    permission: specialmine.admin
    permission-message: §cVous n'avez pas la permission d'utiliser cette commande!

  adminchat:
    description: "Commandes administratives pour gérer le chat"
    usage: /adminchat <mute|unmute|ban|unban|reload|stats|test|broadcast|clear> [arguments]
    permission: specialmine.admin
    permission-message: §cVous n'avez pas la permission d'utiliser cette commande!

  vip:
    description: "Gère les joueurs VIP"
    usage: /vip <add|remove|list|check> [joueur]
    permission: specialmine.admin
    permission-message: §cVous n'avez pas la permission d'utiliser cette commande!
    aliases: [ setvip, managevip ]

  invsee:
    description: "Voir l'inventaire d'un autre joueur"
    usage: /invsee <joueur>
    permission: specialmine.admin
    permission-message: §cVous n'avez pas la permission d'utiliser cette commande!
    aliases: [ inv, openinv, viewinv ]

  enchantbook:
    description: "Accès au système d'enchantements uniques"
    usage: /enchantbook <joueur>"
    permission: specialmine.admin
    permission-message: §cVous n'avez pas la permission d'utiliser cette commande!
    aliases: [ livre ]

  rep:
    description: "Système de réputation"
    usage: /rep [help|voir <joueur>|admin <args>]
    permission: specialmine.basic
    permission-message: §cVous n'avez pas la permission d'utiliser cette commande!
    aliases: [ reputation, repute ]

  fbm:
    description: "Localiser le Black Market"
    usage: /fbm [tp|open|info]
    permission: specialmine.fbm
    permission-message: §cVous n'avez pas la permission d'utiliser cette commande!
    aliases: [ findblackmarket, blackmarket, bm ]

  boost:
    description: Affiche et gère les boosts temporaires
    usage: /<command> [list|admin <type> <durée>]
    permission: specialmine.basic
    permission-message: "§cVous n'avez pas la permission d'utiliser cette commande!"

  voucher:
    description: Donne des vouchers aux joueurs (admin)
    usage: /<command> <joueur> <type> <tier> [quantité]
    permission: specialmine.admin
    permission-message: "§cVous n'avez pas la permission d'utiliser cette commande!"

  giveboost:
    description: Donne des items boost aux joueurs (admin)
    usage: /<command> <joueur> <type> <durée> [bonus] [quantité]
    permission: specialmine.admin
    permission-message: "§cVous n'avez pas la permission d'utiliser cette commande!"

  autominer:
    description: Menu principal des automineurs
    usage: /autominer [give <type>]
    permission: specialmine.basic

  bank:
    description: "Système bancaire complet - épargne, investissements et coffre-fort"
    usage: /bank [deposit|withdraw|invest|safe|improve|help] [args...]
    permission: specialmine.basic
    permission-message: §cVous n'avez pas la permission d'utiliser cette commande!
    aliases: [ banque, banco, bank ]

  tankadmin:
    description: "Commandes d'administration pour les Tanks et Sell Hands"
    usage: "/tankadmin <give|reload> [args...]"
    permission: specialmine.basic
    aliases: [ "ta", "tanks" ]

  gang:
    description: "Commandes principales des gangs"
    usage: "/gang [help|create|invite|...]"
    aliases: [ ]
  g:
    description: "Chat du gang"
    usage: "/g <message>"
    aliases: [ ]
  ap:
    description: "Gestion de l'avant-poste - skins, capture, informations"
    usage: /ap [info|skins|capture|tp|admin|help]
    permission: specialmine.basic
    permission-message: §cVous n'avez pas la permission d'utiliser cette commande!
    aliases: [ avantposte, outpost ]
  warp:
    description: "Téléportation vers les warps"
    usage: "/warp [nom|list|info|gui|help] [args...]"
    permission: specialmine.basic
    aliases: [ warps ]

  menu:
    description: "Ouvre le menu principal"
    usage: "/menu"
    permission: specialmine.basic

  # Modifier la commande mine existante :
  mine:
    description: "Téléportation vers les mines"
    usage: "/mine [nom_mine]"
    permission: specialmine.basic
    aliases: [ mines ]

  spawn:
    description: "Téléportation vers le spawn"
    usage: "/spawn"
    permission: specialmine.basic
    aliases: [ hub ]

  collection:
    description: "Collection de têtes"
    usage: /collection
    permission: specialmine.basic

  quetes:
    description: "Ouvre le menu des quêtes (quotidiennes/hebdomadaires)"
    usage: /quetes [reset]
    permission: specialmine.basic

  battlepassadmin:
    description: "Administration du Pass de combat"
    usage: /bpadmin <start|season|givepremium <joueur>>
    permission: specialmine.admin

  forge:
    description: "Ouvre la Forge"
    usage: /forge
    permission: specialmine.basic

  bpadmin:
    description: ""
    usage: /bpadmin
    permission: specialmine.admin

  daily:
    description: "Ouvre le menu des récompenses journalières"
    usage: /daily
    permission: specialmine.basic
    aliases: [ jour ]

# Compatibilité
depend-bootstrap: false

# Site web et auteur
website: https://github.com/prisontycoon
authors: [ PrisonCore ]